name: feature_documents
description: Personal OS — Documents Feature
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  application: any
  design_system: any
  flutter:
    sdk: flutter
  platform_core: any
  platform_storage: any

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  platform_runtime: any
