include: package:lints/recommended.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - build/**
  errors:
    missing_required_param: error
    missing_return: error
    dead_code: warning

linter:
  rules:
    - always_declare_return_types
    - avoid_dynamic_calls
    - avoid_empty_else
    - avoid_type_to_string
    - cancel_subscriptions
    - close_sinks
    - directives_ordering
    - empty_catches
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - prefer_single_quotes
    - unnecessary_await_in_return
    - unnecessary_lambdas
